"""initial migration

Revision ID: 5bcc00ec0fa7
Revises: 905be1c6ed21
Create Date: 2026-09-27 07:42:58.508489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcc00ec0fa7'
down_revision = '905be1c6ed21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
