"""initial migration

Revision ID: 905be1c6ed21
Revises: 
Create Date: 2026-09-27 07:42:16.605701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '905be1c6ed21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'BUYER', 'ADMIN', 'COMMUNITY_MEMBER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('farmer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('farmer_info', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('size_acres', sa.Float(), nullable=True),
    sa.Column('soil_info', sa.String(length=500), nullable=True),
    sa.Column('water_availability', sa.Enum('ABUNDANT', 'MODERATE', 'LIMITED', 'NONE', name='wateravailability'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_owner_id'), 'farms', ['owner_id'], unique=False)
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'PLANTED', 'GROWING', 'READY_FOR_HARVEST', 'HARVESTED', 'FAILED', name='cropstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crops_farm_id'), 'crops', ['farm_id'], unique=False)
    op.create_table('crop_history_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=150), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_history_entries_crop_id'), 'crop_history_entries', ['crop_id'], unique=False)
    op.create_table('disease_detection_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('predicted_disease', sa.String(length=150), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_backend_used', sa.String(length=50), nullable=False),
    sa.Column('raw_model_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_detection_records_crop_id'), 'disease_detection_records', ['crop_id'], unique=False)
    op.create_index(op.f('ix_disease_detection_records_farmer_id'), 'disease_detection_records', ['farmer_id'], unique=False)
    op.create_table('farmer_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.Enum('WATERLOGGING', 'DROUGHT', 'SALINITY', 'PEST_OUTBREAK', 'DISEASE_OUTBREAK', 'UNEXPECTED_WEATHER', 'CROP_GROWTH_PROBLEM', 'OTHER', name='feedbacktype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_feedback_crop_id'), 'farmer_feedback', ['crop_id'], unique=False)
    op.create_index(op.f('ix_farmer_feedback_farm_id'), 'farmer_feedback', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farmer_feedback_farmer_id'), 'farmer_feedback', ['farmer_id'], unique=False)
    op.create_table('pest_detection_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('predicted_pest', sa.String(length=150), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_backend_used', sa.String(length=50), nullable=False),
    sa.Column('raw_model_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pest_detection_records_crop_id'), 'pest_detection_records', ['crop_id'], unique=False)
    op.create_index(op.f('ix_pest_detection_records_farmer_id'), 'pest_detection_records', ['farmer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pest_detection_records_farmer_id'), table_name='pest_detection_records')
    op.drop_index(op.f('ix_pest_detection_records_crop_id'), table_name='pest_detection_records')
    op.drop_table('pest_detection_records')
    op.drop_index(op.f('ix_farmer_feedback_farmer_id'), table_name='farmer_feedback')
    op.drop_index(op.f('ix_farmer_feedback_farm_id'), table_name='farmer_feedback')
    op.drop_index(op.f('ix_farmer_feedback_crop_id'), table_name='farmer_feedback')
    op.drop_table('farmer_feedback')
    op.drop_index(op.f('ix_disease_detection_records_farmer_id'), table_name='disease_detection_records')
    op.drop_index(op.f('ix_disease_detection_records_crop_id'), table_name='disease_detection_records')
    op.drop_table('disease_detection_records')
    op.drop_index(op.f('ix_crop_history_entries_crop_id'), table_name='crop_history_entries')
    op.drop_table('crop_history_entries')
    op.drop_index(op.f('ix_crops_farm_id'), table_name='crops')
    op.drop_table('crops')
    op.drop_index(op.f('ix_farms_owner_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_table('farmer_profiles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
